---

- name: install dependencies
  ansible.builtin.apt:
    name:
      - libdbd-mysql-perl
      - libcache-cache-perl
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: fix munin plugin for mysql 5.7
  ansible.builtin.get_url:
     url: https://raw.githubusercontent.com/munin-monitoring/munin/master/plugins/node.d/mysql_
     dest: /usr/share/munin/plugins/mysql_
     mode: "a+x"
     force: yes
  become: yes

- name: add mysql_commands plugin
  ansible.builtin.file:
    src: /usr/share/munin/plugins/mysql_
    dest: /etc/munin/plugins/mysql_commands
    state: link
  notify: restart_munin_node
  become: yes

- name: add mysql_connections plugin
  ansible.builtin.file:
    src: /usr/share/munin/plugins/mysql_
    dest: /etc/munin/plugins/mysql_connections
    state: link
  notify: restart_munin_node
  become: yes

- name: add mysql_network_traffic plugin
  ansible.builtin.file:
    src: /usr/share/munin/plugins/mysql_
    dest: /etc/munin/plugins/mysql_network_traffic
    state: link
  notify: restart_munin_node
  become: yes

- name: add munin plugin-conf
  ansible.builtin.copy:
    content: |
      [mysql*]
      user root
      env.mysqlopts ""
      env.mysqluser root
    dest: /etc/munin/plugin-conf.d/mysql_
    mode: 0644
  notify: restart_munin_node
  become: yes
