---

- name: create override folder
  ansible.builtin.file:
    state: directory
    path: /etc/systemd/system/mysql.service.d
    mode: '0755'
  become: yes

- name: copy system override
  ansible.builtin.template:
    src: override.ini
    dest: /etc/systemd/system/mysql.service.d/override.conf
    mode: '0644'
  become: yes
  notify:
    - reload_systemd
    - restart_mysql
