---

version: 2.1

jobs:

  build:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      image: ubuntu-2004:202201-02
    environment:
      ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

    steps:
      - run: pip3 install ansible ansible-lint

      - run: ansible --version
      - run: ansible-lint --version

      - run: ansible-galaxy collection install community.mysql

      - checkout

      - run: printf '[defaults]\nroles_path=../' > ansible.cfg

      - run: ansible-lint
      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local
      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local

      - run: sudo journalctl --unit=mysql
      - run: sudo cat /var/log/mysql/error.log
      - run: mysql --version
      - run: mysql -h127.0.0.1 -utradmin -ptest -e 'SELECT VERSION();'
      - run: mysql -h127.0.0.1 -utradmin -ptest -e 'SHOW DATABASES;'
